access:
  token.validity.seconds: 86400

oauth:
  signing:
    key: ierslcjer34ksd30987sdlsdjhsdh

security:
  basic:
    enabled: false

api:
  request:
    origin: http://localhost:8082

